-- MySQL Script generated by MySQL Workbench
-- Sat Sep  7 15:53:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Crawler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Crawler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Crawler` DEFAULT CHARACTER SET utf8 ;
USE `Crawler` ;

-- -----------------------------------------------------
-- Table `Crawler`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crawler`.`site` (
  `url` VARCHAR(200) NOT NULL,
  `rank` INT NOT NULL DEFAULT 0,
  `title` VARCHAR(50) NOT NULL,
  `fav` VARCHAR(100) NULL,
  `h` VARCHAR(100) NULL,
  `s/b` VARCHAR(100) NULL,
  `p` VARCHAR(400) NULL,
  `div` VARCHAR(400) NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
